### ISSUE TITLE
02: getting root

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-root#2]
Comments for https://cms-opendata-workshop.github.io/workshop-lesson-root/02-get-root/index.html

- [x] Remove ", in batch systems and CIs" from the intro sentence: This section shows you multiple ways to get ROOT. Find below solutions to run ROOT locally, on your VM or Docker container, in batch systems and CIs!

"CVMFS":

- [x] the first section "CVMFS" is about running root on the CMS open data environments. Can the title be changed to "Root on the CMS open data environments" to reflect that?

- [x] for the open data envs, this : "Note the platform and compiler dependent information in the path, which have to be adjusted based on your system. The available combinations are shown on the website." is not needed, right? This can be quite confusing for those who just run root on VM or docker. 

- [x] root works on the "Outer shell" shell of VM as well, i would instruct to run it there. I had some trouble opening it on the CMS Shell, maybe it was just (really) slow?

- [x] Are the explanatory three sentences really needed?  Could that first part start with "The following setup line works in the SLC6 shell open data VM and Docker container (if the cvmfs has been mounted to the container)" Or can they be separated to a specific section for cases mounting cvmfs locally?

"Docker"

- [x] pinging @stwunsch to know if a root container with c++14 could be made available?

**Comment by katilp** [comment]
- [x] Change to `docker run --rm -it rootproject/root:6.22.02-conda /bin/bash`

**Comment by caredg** [comment]
I have made the requested changes and/or clarify the statements.
