### ISSUE TITLE
Comments on ROOT in C++ and Python

### ISSUE THREAD

**Issue by Mmintyyy** [cms-opendata-workshop/workshop-lesson-root#3]
### ROOT in C++ and Python

**The ROOT prompt**
- I did not manage to see the pictures of histograms or other plots in virtual machine environment when running the commands (and it did not work in Docker either as told in previous comments). I tried using both, CMS Shell (SLC 6) and Outer Shell (SLC 7), but could not make it work. Kati advised me to save the graphs as picture files instead by changing the myScript.C code provided in the next ROOT scripts section a bit, and this approach worked.

**ROOT scripts**
- In this part overall, it took a lot of time for me to be able to run the scripts, as I could not modify the files in root prompt as the vi editor does not work there, and when working in the virtual environment, I did not know how to create the files in editor on my host computer so that I would be able to access them through a virtual machine or WSL
- I ended up using the EOS/CERNBox file sharing environment with the virtual machine, but Kati needed to walk me through on how to use it. It might be useful to add instructions for this, or provide the scripts in ready made files so that the users could just run them without a need to create the files themselves.
	○ Example of how I would do the process:
		 § Create files (e.g. myScript.C) in text editor in my host computer and save them to https://cernbox.cern.ch
		 § On the virtual machine command line, use command: ssh ntanska@lxplus.cern.ch 
		 § Once logged in, navigate to the right directory with command: cd /eos/user/n/ntanska
		 § Run the code in the virtual machine (e.g. "root -l myScript.C")
			
**Compiled C++**
- "Now, let’s compile and run the script again. Note the + after the script name!"
○ I thought you needed to rename the file here as myScript.C+ and ran into some problems with that, so it could be specified that you don't need to change the filename but to use "+" only in the command

**Comment by caredg** [comment]
@katilp and @Mmintyyy, would a dump [like this](https://cms-opendata-workshop.github.io/workshop-lesson-root/files/lessonDump.txt) work? One could download this file, in the vm, have it open while doing the exercises and follow along...
@Mmintyyy, I suppose you can get an editor (btw in the virtual machine there is also nano and emacs while in docker there is only vi) from another terminal window, right? I had added this note in the VM instructions after you reported your difficulties with vi: "Note that other editors like emacs or nano are also avilable in the VM."

**Comment by caredg** [comment]
I' ve made a clarifying note about the + sign.

**Comment by katilp** [comment]
@caredg that dump is great. I was thinking of selecting bash commands, but the full dump is actually better as one can see the context.

**Comment by Mmintyyy** [comment]
@caredg Good to know, I had missed that change about the editors! I tried nano in the VM and it worked fine. Adding the dump file you suggested with necessary instructions (how to access the file in VM) should then solve the problem, as people could copy paste commands and scripts from there when needed inside the VM.

Instructing the users on how to access host local files in VM or WSL could be useful if considering future use of these tools for the participants. However, it might be better to have separate instructions for that, than include them in this pre-exercise, now that it should work fine with the dump file.

**Comment by caredg** [comment]
> @caredg that dump is great. I was thinking of selecting bash commands, but the full dump is actually better as one can see the context.

Ok, then I will make one dump for each of the pre-exercises and make a note in the pre-exercises header about the dumps and possibly in the Setup sections
