### ISSUE TITLE
Comments on Commonly used features in ROOT

### ISSUE THREAD

**Issue by Mmintyyy** [cms-opendata-workshop/workshop-lesson-root#7]
### Commonly used features in ROOT

**The rootbrowse executable**

- [ ]  rootbrowse command did not open a window with the directory for me, at least when working on the command line in the lxplus environment with a virtual machine. TBrowser command did not work in the lxplus environment either, but I managed to open the TBrowser view in the Outer Shell of the virtual machine (without access to relevant files though as I had saved them in lxplus).

**Comment by caredg** [comment]
I will recommend to use the Outer Shell then

**Comment by caredg** [comment]
closed via 8a3fd3d4c9063cd7cb9a1e31cfaa9cbae91f87eb
