### ISSUE TITLE
From the mattermost chat: error in the jupyter notebook?

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-root#9]
In [the mattermost chat](https://mattermost.web.cern.ch/cmsopendatatheo/channels/root-pre-exercise), a user reports an error in the jupyter notebook, likely referring the one suggested in 05, i.e. https://mybinder.org/v2/gh/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/master?filepath=dimuonSpectrum.ipynb

@stwunsch I can reproduce that.
 - Is this related to what we discussed a while ago with the binder team and what was fixed  `ROOT.ROOT.EnableImplicitMT(1)` or something different.

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-4-29596316c4b5> in <module>
----> 1 df_2mu = df.Filter("nMuon == 2", "Events with exactly two muons")

Exception: ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Filter(basic_string_view<char,char_traits<char> > expression, basic_string_view<char,char_traits<char> > name = "") =>
    Cannot interpret the following expression:
nMuon == 2

Make sure it is valid C++. (C++ exception of type runtime_error)

Error in <TUnixSystem::GetHostByName>: getaddrinfo failed for 'eospublic.cern.ch': Temporary failure in name resolution
Error in <TNetXNGFile::Open>: [FATAL] Invalid address
input_line_90:1:46: error: use of undeclared identifier 'nMuon'
namespace __tdf_0{ auto tdf_f = []() {return nMuon == 2
                                             ^
```

**Comment by katilp** [comment]
@tiborsimko Has something changed for the file access/location? The notebook reads `root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root`

**Comment by tiborsimko** [comment]
No change in the file access; the path is OK and I can download this file fine

**Comment by katilp** [comment]
For the record, the earlier problem I'm referring to was discussed under https://discourse.jupyter.org/t/a-repo-failing-to-access-a-file-tnetxngfile-open-fatal-connection-error/2841

**Comment by katilp** [comment]
Retrying, and the notebooks ending up both in
https://notebooks.gesis.org/binder/jupyter/...
and https://hub.gke2.mybinder.org/user/... run fine. It must have a been a temporary problem or something that has been fixed to address the earlier error:

`Error in <TUnixSystem::GetHostByName>: getaddrinfo failed for 'eospublic.cern.ch': Temporary failure in name resolution`
